language: ruby
rvm:
 - 2.5.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
